# Generated by Django 5.1.2 on 2024-10-29 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Intent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_label', models.CharField(max_length=255)),
                ('expectation_id', models.CharField(max_length=255)),
                ('expectation_verb', models.CharField(max_length=50)),
                ('object_type', models.CharField(max_length=50)),
                ('context_attributes', models.JSONField()),
                ('target_metrics', models.JSONField()),
                ('priority', models.CharField(max_length=50)),
                ('observation_period', models.CharField(max_length=50)),
                ('report_reference', models.CharField(max_length=255)),
            ],
        ),
    ]
