# Generated by Django 5.2.8 on 2025-12-03 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NaturalIntent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=20)),
                ('intent', models.CharField(max_length=50)),
                ('timestamp', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='NetworkIntent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('mac_address', models.CharField(blank=True, max_length=17, null=True)),
                ('ipv4_start', models.GenericIPAddressField(blank=True, null=True, protocol='IPv4')),
                ('ipv4_end', models.GenericIPAddressField(blank=True, null=True, protocol='IPv4')),
                ('ipv6_start', models.GenericIPAddressField(blank=True, null=True, protocol='IPv6')),
                ('ipv6_end', models.GenericIPAddressField(blank=True, null=True, protocol='IPv6')),
            ],
        ),
    ]
