# Generated by Django 5.2.8 on 2025-12-03 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intentString', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PolicyIntent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=100)),
                ('expectation_object', models.CharField(max_length=200)),
                ('expectation_target', models.CharField(max_length=200)),
                ('head', models.CharField(max_length=200)),
                ('relation', models.CharField(max_length=200)),
                ('tail', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
