# Generated by Django 5.2.8 on 2025-11-27 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intentString', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NetworkIntent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('mac_address', models.CharField(blank=True, max_length=17, null=True)),
                ('ipv4_start', models.GenericIPAddressField(blank=True, null=True, protocol='IPv4')),
                ('ipv4_end', models.GenericIPAddressField(blank=True, null=True, protocol='IPv4')),
                ('ipv6_start', models.GenericIPAddressField(blank=True, null=True, protocol='IPv6')),
                ('ipv6_end', models.GenericIPAddressField(blank=True, null=True, protocol='IPv6')),
            ],
        ),
        migrations.RenameModel(
            old_name='IntentString',
            new_name='NaturalIntent',
        ),
    ]
