# Generated by Django 5.2.8 on 2025-12-23 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intentString', '0002_policyintent'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicationIntent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_label', models.CharField(blank=True, max_length=30, null=True)),
                ('expectation_id', models.CharField(blank=True, max_length=10, null=True)),
                ('expectation_verb', models.CharField(blank=True, max_length=10, null=True)),
                ('object_type', models.CharField(blank=True, max_length=10, null=True)),
                ('targer_SDV_id', models.JSONField(blank=True, null=True)),
                ('speed', models.IntegerField(blank=True, null=True)),
                ('priority', models.IntegerField(blank=True, null=True)),
                ('location', models.CharField(blank=True, max_length=30, null=True)),
                ('observation_period', models.IntegerField(blank=True, null=True)),
                ('report_reference', models.CharField(blank=True, max_length=30, null=True)),
            ],
        ),
    ]
