# Generated by Django 5.2.8 on 2025-12-04 04:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intentString', '0002_networkintent_rename_intentstring_naturalintent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='naturalintent',
            name='intent',
            field=models.CharField(max_length=300),
        ),
        migrations.CreateModel(
            name='IntentInference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intent_action', models.CharField(blank=True, max_length=255, null=True)),
                ('intent_expectation_object', models.CharField(blank=True, max_length=255, null=True)),
                ('intent_expectation_target', models.CharField(blank=True, max_length=255, null=True)),
                ('kg_head', models.CharField(blank=True, max_length=255, null=True)),
                ('kg_relation', models.CharField(blank=True, max_length=255, null=True)),
                ('kg_tail', models.CharField(blank=True, max_length=255, null=True)),
                ('confidence', models.FloatField(blank=True, null=True)),
                ('degraded', models.BooleanField(default=False)),
                ('degradation_note', models.TextField(blank=True, null=True)),
                ('timestamp', models.DateTimeField()),
                ('natural_intent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='intentString.naturalintent')),
                ('network_intent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='intentString.networkintent')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
