# Generated by Django 5.2.8 on 2025-12-23 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intentString', '0003_applicationintent'),
    ]

    operations = [
        migrations.RenameField(
            model_name='applicationintent',
            old_name='targer_SDV_id',
            new_name='context_targer_id',
        ),
        migrations.RenameField(
            model_name='applicationintent',
            old_name='speed',
            new_name='target_value',
        ),
        migrations.AddField(
            model_name='applicationintent',
            name='context_attribute',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='applicationintent',
            name='context_condition',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='applicationintent',
            name='target_condition',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='applicationintent',
            name='target_name',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
