# Generated by Django 5.2.8 on 2025-12-04 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intentString', '0003_alter_naturalintent_intent_intentinference'),
    ]

    operations = [
        migrations.AddField(
            model_name='networkintent',
            name='timestamp',
            field=models.DateTimeField(default='2025-12-04 00:00:00'),
            preserve_default=False,
        ),
    ]
