# Generated by Django 5.2.8 on 2025-12-04 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intentString', '0004_networkintent_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='naturalintent',
            name='timestamp',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='networkintent',
            name='timestamp',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
